### PR TITLE
Back from school to WORK! ...so hard...

### PR DESCRIPTION
**Pull request by MarikCZ**
Title saya everything. Few importnant test are become, but I learnt for it very long time, so it couldn't be hard. I don't what is actually merged and how, where is new master-branch repository... I think you can merge it by one click, nothing will cause.

The last thing - I am really amazed by masssive amount of project thats are started by you! Good luck in making it! ;)

Best regards

old forgot_ Marik

### CODE REVIEW

**Comment by xMrVizzy** [comment]
I will take good texture and pull yourself, and credit you in PR

**Comment by xMrVizzy** [comment]
Now I will create another branch and If you wan't you can update 1.11 version!!!!! I will create 1.12

**Comment by MarikCZ** [comment]
Hi xMrVizzy

Thank you for good news!!! I'll forget on 1.10 and I'll glad to help you
with updating textures! You just will create new 1.12 repository with logo
and mcmeta file, and textures I'll update - it will be easy and you won't
be scared by ugly textures. ;)

Best regards
Marik

Dne 14. 6. 2017 18:03 napsal uživatel "Alexey Krainev" <
notifications@github.com>:

Now I will create another branch and If you wan't you can update 1.11
version!!!!! I will create 1.12

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/XVTEAM/FaithfulMods/pull/8#issuecomment-308478538>, or mute
the thread

**Comment by xMrVizzy** [comment]
I already created another branch for 1.12

**Comment by MarikCZ** [comment]
Sorry I overlooked. :)

**Comment by MarikCZ** [comment]
Actually I must wate to 1.12 Forge and mods releases. Maybe I could learn how to write my own mods... Eclipse is already setted up... NONONO - it it will be better, if I stay helping with pack. I really don't want to see, how I'm devastating your work and plans in Mods... :D

**Pull request closed without merging**
